# Header
menu:
  Home: /
  Archives: /archives
rss: /atom.xml

# Content
excerpt_link: Read More
fancybox: true

# Sidebar
sidebar: bottom
widgets:
- recent_posts
#- category
- tag
#- tagcloud
- archive


# Miscellaneous
google_analytics: UA-59725882-1
favicon: /favicon.png
twitter:
google_plus:
fb_admins:
fb_app_id: